Mobile-Portfolio-setup
Hsuwaddyhtat22/Portfolio pull request #2
Opened 2023-06-02 16:42 UTC by Hsuwaddyhtat22

In this mobile portfolio project. I make these actions . See in below.
-Add HTML styles
-Add CSS
(I used most of Css )
-Linters
_Figma Template

2023-06-02 19:03 UTC, christianbiring1 requested changes
Hi @Hsuwaddyhtat22 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
# STATUS: REQUEST CHANGES :recycle: 


## Highlights
- [ ] Great work on implementing the work and about section :+1: 
- [ ] Descriptive PR `title` and `summary` :+1: 
- [ ] All linters checks are passing :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._
- [ ] Kindly make sure you stick to the original design. the spacing(margin, padding) and typos(fonts)  are supposed to be similar to the original Figma design.
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 01:30 UTC, Hsuwaddyhtat22 commented on index.html
> +                </li>
@christianbiring1 
Plz can you show me with example how should I do actually I don't understand what did you mean?

2023-06-03 01:52 UTC, Hsuwaddyhtat22 commented
Hello,I sent a message on GitHub ,can you check plz I am urgent

On Sat, 3 Jun 2023, 1:33 am Christian Biringanine, ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @Hsuwaddyhtat22 <https://github.com/Hsuwaddyhtat22> ,
>
> Good job so far!
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
> STATUS: REQUEST CHANGES ♻️ Highlights
>
>    - Great work on implementing the work and about section 👍
>    - Descriptive PR title and summary 👍
>    - All linters checks are passing ✔️
>
> Required Changes ♻️
>
> *Check the comments under the review.*
>
>    - Kindly make sure you stick to the original design. the
>    spacing(margin, padding) and typos(fonts) are supposed to be similar to the
>    original Figma design.
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/Hsuwaddyhtat22/Portfolio/pull/2#discussion_r1214711119>
> :
>
> > +            </header>
> +            <img src="image/Project Title.png" alt="" id="tonic">
> +            <section>
> +                <div class="title">
> +                    <ul>
> +                        <li>
> +                            <a href="#"><img src="image/Text.png" alt=""></a>
> +                        </li>
> +                        <li>
> +                            <a href="#"><img src="image/Counter.png" alt=""></a>
> +                        </li>
> +                        <li>
> +                            <a href="#"><img src="image/Role.png" alt=""></a>
> +                        </li>
> +                        <li>
> +                            <a href="#"><img src="image/Counter.png" alt=""></a>
> +                        </li>
> +                        <li>
> +                            <a href="#"><img src="image/Year Label.png" alt=""></a>
> +                        </li>
> +                    </ul>
>
>
>    - Kindly make sure you use semantic tags on your page. these elements
>    you are not supposed to implement them as images as you did. you are
>    supposed to use simple markup elements as the project title is supposed to
>    be a heading tag hx and not an image.
>    You are not supposed to use the images as you did. Kindly correct that.
>
> ------------------------------
>
> In index.html
> <https://github.com/Hsuwaddyhtat22/Portfolio/pull/2#discussion_r1214712244>
> :
>
> > +                <ul class="categories">
> +                    <li>
> +                        <a href="#"><img src="image/Tag.png" alt=""></a>
> +                    </li>
> +                    <li>
> +                        <a href="#"><img src="image/Tag-1.png" alt=""></a>
> +                    </li>
> +                    <li>
> +                        <a href="#"><img src="image/Tag-2.png" alt=""></a>
> +                    </li>
> +                </ul>
>
>
>    - Kindly make sure you use semantic tags on your page. these elements
>    you are not supposed to implement them as images as you did. you are
>    supposed to use simple markup elements.
>    You are not supposed to use the images as you did. Kindly correct that.
>
> ------------------------------
>
> In index.html
> <https://github.com/Hsuwaddyhtat22/Portfolio/pull/2#discussion_r1214712487>
> :
>
> > +    <div class="version2">
> +        <header class="sec">
> +            <img src="image/snap.png" alt="" class="iconic">
> +        </header>
> +        <img src="image/p title2.png" alt="" id="tonic">
> +        <section>
> +            <div class="title">
> +                <ul>
> +                    <li>
> +                        <a href="#"><img src="image/Text.png" alt=""></a>
> +                    </li>
> +                    <li>
> +                        <a href="#"><img src="image/Counter.png" alt=""></a>
> +                    </li>
> +                    <li>
> +                        <a href="#"><img src="image/Role.png" alt=""></a>
> +                    </li>
> +                    <li>
> +                        <a href="#"><img src="image/Counter.png" alt=""></a>
> +                    </li>
> +                    <li>
> +                        <a href="#"><img src="image/Year Label.png" alt=""></a>
> +                    </li>
> +                </ul>
>
>
>    - Kindly make sure you use semantic tags on your page. these elements
>    you are not supposed to implement them as images as you did. you are
>    supposed to use simple markup elements.
>    You are not supposed to use the images as you did. Kindly correct that.
>
> ------------------------------
>
> In index.html
> <https://github.com/Hsuwaddyhtat22/Portfolio/pull/2#discussion_r1214712772>
> :
>
> > +            </div>
> +            <ul class="categories">
> +                <li>
> +                    <a href="#"><img src="image/Tag.png" alt=""></a>
> +                </li>
> +                <li>
> +                    <a href="#"><img src="image/Tag-1.png" alt=""></a>
> +                </li>
> +                <li>
> +                    <a href="#"><img src="image/Tag-2.png" alt=""></a>
> +                </li>
> +            </ul>
> +            <button id="seepj"><img src="image/See project.png" alt=""></button>
>          </section>
> +    </div>
> +    <div class="version2">
> +        <header class="sec">
> +            <img src="image/Snapshoot Portfolio (2).png" alt="" class="iconic">
> +        </header>
> +        <img src="image/p title2.png" alt="" id="tonic">
> +        <section>
> +            <div class="title">
> +                <ul>
> +                    <li>
> +                        <a href="#"><img src="image/Text.png" alt=""></a>
> +                    </li>
> +                    <li>
>
>
>    - Kindly make sure you use semantic tags on your page. these elements
>    you are not supposed to implement them as images as you did. you are
>    supposed to use simple markup elements.
>    You are not supposed to use the images as you did. Kindly correct that.
>
> ------------------------------
>
> In index.html
> <https://github.com/Hsuwaddyhtat22/Portfolio/pull/2#discussion_r1214713170>
> :
>
> > +                    </li>
> +                    <li>
> +                        <a href="#"><img src="image/Role.png" alt=""></a>
> +                    </li>
> +                    <li>
> +                        <a href="#"><img src="image/Counter.png" alt=""></a>
> +                    </li>
> +                    <li>
> +                        <a href="#"><img src="image/Year Label.png" alt=""></a>
> +                    </li>
> +                </ul>
> +            </div>
> +            <div id="line">
> +                <pre>A daily selection of privately</pre>
> +                <pre>info personalized reads; no accounts </pre>
> +                <pre>or sign-ups required.</pre>
> +            </div>
> +            <ul class="categories">
> +                <li>
> +                    <a href="#"><img src="image/ [...]

2023-06-03 05:20 UTC, Hsuwaddyhtat22 commented
I used icons only with image because I think it is good and easy to use

2023-06-03 06:21 UTC, shella12 requested changes
Hi @Hsuwaddyhtat22 , 

Great work on making the changes requested by a previous reviewer 👏 👏 👏 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet. You are almost there...

<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights

- Fair attempt at design implementation ✅   

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 06:21 UTC, shella12 commented on index.html
> +                <button id="seepj"><img src="image/final/Get my resume.png" alt=""></button>
- [ ]  Again here to put any text inside `button` tag you don't need to use image. Just use plain text that way it would be easier for you to customise the button text and style. Example snippet:

```html
<button id="seepj">See project</button>
```

2023-06-03 06:21 UTC, shella12 commented on index.html
> +                </div>
- [ ] Here as well please use plain text instead of `images `, for lines you can use `<hr>` element or simple border-bottom in CSS, for icons like down-arrows or language icons you can use images.  and to layout all the elements you can use `flexbox`. Example snippet:

```html
<ul>
                    <li>
                        <h3>Languages</h3>h3>
                        <img src="down-icon.png" alt="icon down" />
                        <ul>
                            <li>
                                <img src="image/final/Frame 9.png" alt="" />
                            </li>
                            <li>
                                <img src="image/final/Frame 10.png" alt="" />
                            </li>
                            <li>
                                <img src="image/final/Frame 11.png" alt="" />
                            </li>
                        </ul>
                    </li>
                    <li>Skills</li>
                    <li>Frameworks</li>
                </ul>
```

2023-06-03 09:25 UTC, Cabraham1 reviewed
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Hey @shahadat3669  :wave:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following Gitflow
✔️ Following some requirements

Good job on implementing some of the requirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

- [ ] I kindly request that you adhere to the Figma design provided for your project. The Figma design serves as a visual reference and guideline for implementing the desired user interface and overall look of your application. Please ensure that the implemented code aligns with the design specifications provided in Figma. This includes aspects such as layout, color scheme, typography, and any other visual elements defined in the design.
- [ ] Your Design
- [ ] your design here is incomplete
![image](https://github.com/Hsuwaddyhtat22/Portfolio/assets/68823331/d473d1f4-51ac-47f2-b507-0de1ba9fa5ab)
![image](https://github.com/Hsuwaddyhtat22/Portfolio/assets/68823331/76f77a97-def7-474e-9c2b-a1bfcfbf75cd)
![image](https://github.com/Hsuwaddyhtat22/Portfolio/assets/68823331/bd323c60-e572-4025-993c-3ede44dc53ed)
![image](https://github.com/Hsuwaddyhtat22/Portfolio/assets/68823331/d56de956-b955-4645-9755-2e45f90e26f0)



- [ ] Microverse Figma Design

![image](https://github.com/Hsuwaddyhtat22/Portfolio/assets/68823331/05b7d8fe-0e80-4722-b956-dd572cfb0a2c)
![image](https://github.com/Hsuwaddyhtat22/Portfolio/assets/68823331/601116fd-6312-434e-aef6-51a23ff3eba2)
![image](https://github.com/Hsuwaddyhtat22/Portfolio/assets/68823331/7cce31a6-7ab2-4080-ba08-1b553db84fff)


# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers, and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 09:25 UTC, Cabraham1 commented on style.css
> +}
- [ ] I understand that a previous reviewer has already identified the discrepancy between the project requirement and the provided implementation. The requirement specifies that the content of the project should be aligned using flexbox, but it appears that this has not been implemented.

2023-06-03 09:25 UTC, Cabraham1 commented on index.html
> +            </ul>
- [ ] [OPTIONAL] Certainly! As a code reviewer, I noticed that the implementation includes buttons for the list of project technologies, which does not align with the project requirement. The requirement states that the list should be represented as an unordered list (`<ul>`) with each technology as a list item (`<li>`).

Using buttons for the list of project technologies may introduce unnecessary interactivity or confusion to users since buttons are typically associated with actions. In this case, it would be more appropriate to utilize list items to represent the technologies.

To address this, I recommend replacing the buttons with list items (`<li>`) within an unordered list (`<ul>`) to adhere to the project requirement. This will improve the semantic structure of the code and ensure better accessibility.

Here's an example of how the code should be structured:

```html
<ul>
  <li>JavaScript</li>
  <li>HTML</li>
  <li>CSS</li>
</ul>
```

By making this adjustment, the code will align with the project requirement and adhere to best practices for HTML structure.

2023-06-03 09:25 UTC, Cabraham1 commented on index.html
> +            </ul>
- [ ] [OPTIONAL] Certainly! As a code reviewer, I noticed that the implementation includes buttons for the list of project technologies, which does not align with the project requirement. The requirement states that the list should be represented as an unordered list (`<ul>`) with each technology as a list item (`<li>`).

Using buttons for the list of project technologies may introduce unnecessary interactivity or confusion to users since buttons are typically associated with actions. In this case, it would be more appropriate to utilize list items to represent the technologies.

To address this, I recommend replacing the buttons with list items (`<li>`) within an unordered list (`<ul>`) to adhere to the project requirement. This will improve the semantic structure of the code and ensure better accessibility.

Here's an example of how the code should be structured:

```html
<ul>
  <li>JavaScript</li>
  <li>HTML</li>
  <li>CSS</li>
</ul>
```

By making this adjustment, the code will align with the project requirement and adhere to best practices for HTML structure.

2023-06-03 09:25 UTC, Cabraham1 commented on index.html
> +            </ul>
- [ ] [OPTIONAL] Certainly! As a code reviewer, I noticed that the implementation includes buttons for the list of project technologies, which does not align with the project requirement. The requirement states that the list should be represented as an unordered list (`<ul>`) with each technology as a list item (`<li>`).

Using buttons for the list of project technologies may introduce unnecessary interactivity or confusion to users since buttons are typically associated with actions. In this case, it would be more appropriate to utilize list items to represent the technologies.

To address this, I recommend replacing the buttons with list items (`<li>`) within an unordered list (`<ul>`) to adhere to the project requirement. This will improve the semantic structure of the code and ensure better accessibility.

Here's an example of how the code should be structured:

```html
<ul>
  <li>JavaScript</li>
  <li>HTML</li>
  <li>CSS</li>
</ul>
```

By making this adjustment, the code will align with the project requirement and adhere to best practices for HTML structure.

2023-06-03 09:25 UTC, Cabraham1 commented on index.html
> +            </ul>
- [ ] [OPTIONAL] Certainly! As a code reviewer, I noticed that the implementation includes buttons for the list of project technologies, which does not align with the project requirement. The requirement states that the list should be represented as an unordered list (`<ul>`) with each technology as a list item (`<li>`).

Using buttons for the list of project technologies may introduce unnecessary interactivity or confusion to users since buttons are typically associated with actions. In this case, it would be more appropriate to utilize list items to represent the technologies.

To address this, I recommend replacing the buttons with list items (`<li>`) within an unordered list (`<ul>`) to adhere to the project requirement. This will improve the semantic structure of the code and ensure better accessibility.

Here's an example of how the code should be structured:

```html
<ul>
  <li>JavaScript</li>
  <li>HTML</li>
  <li>CSS</li>
</ul>
```

By making this adjustment, the code will align with the project requirement and adhere to best practices for HTML structure.

2023-06-03 15:03 UTC, Hsuwaddyhtat22 commented
I try my best . I did not add some features ex. down-button like that because I can't use img tag on ul and li. So I want you to understand

2023-06-03 15:20 UTC, Cabraham1 requested changes
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Hey @Hsuwaddyhtat22   :wave:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following Gitflow
✔️ Following some requirements

Good job on implementing some of the requirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

- [ ] I kindly request that you adhere to the Figma design provided for your project. The Figma design serves as a visual reference and guideline for implementing the desired user interface and overall look of your application. Please ensure that the implemented code aligns with the design specifications provided in Figma. This includes aspects such as layout, color scheme, typography, and any other visual elements defined in the design.
- [ ] Your Design
- [ ] your design here is incomplete
![image](https://github.com/Hsuwaddyhtat22/Portfolio/assets/68823331/d473d1f4-51ac-47f2-b507-0de1ba9fa5ab)



- [ ] Microverse Figma Design

![image](https://github.com/Hsuwaddyhtat22/Portfolio/assets/68823331/05b7d8fe-0e80-4722-b956-dd572cfb0a2c)
![image](https://github.com/Hsuwaddyhtat22/Portfolio/assets/68823331/601116fd-6312-434e-aef6-51a23ff3eba2)

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers, and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 15:20 UTC, Cabraham1 commented on index.html
> +            </ul>
- I have observed that you are utilizing a period as a dot in this particular instance. However, as per the project requirements, it is expected that you utilize an icon instead of the ` . ` characters. I highly recommend implementing this adjustment. 😉

- Kindly consider utilizing flex, margin, and padding to effectively align the elements.

2023-06-03 15:20 UTC, Cabraham1 commented on index.html
> +            </ul>
- I have observed that you are utilizing a period as a dot in this particular instance. However, as per the project requirements, it is expected that you utilize an icon instead of the ` . ` characters. I highly recommend implementing this adjustment. 😉

- Kindly consider utilizing flex, margin, and padding to effectively align the elements.

2023-06-03 15:20 UTC, Cabraham1 commented on index.html
> +                <li>.2015</li>
- I have observed that you are utilizing a period as a dot in this particular instance. However, as per the project requirements, it is expected that you utilize an icon instead of the ` . ` characters. I highly recommend implementing this adjustment. 😉

- Kindly consider utilizing flex, margin, and padding to effectively align the elements.

2023-06-03 22:18 UTC, Tufahel approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

Hi @Hsuwaddyhtat22 :wave: 
 
Well done implementing the changes. 👍 
Your project is complete now!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 👏🏻

![](https://media0.giphy.com/media/d31w24psGYeekCZy/giphy.gif?cid=ecf05e47zaer8jfqmid0gfxhz2oq4gcjqy2c2aol3ldn6gvl&rid=giphy.gif&ct=g)

:heavy_check_mark: Descriptive pull request.
:heavy_check_mark: Correct GitHub flow.
:heavy_check_mark: Commit messages are meaningful.

## Optional suggestions 🤷‍♂️

- [ ] ***[OPTIONAL]*** Kindly give padding/margin between the cards and give some margin to the left.
- ***Given Figma Design***
- ![image](https://github.com/Hsuwaddyhtat22/Portfolio/assets/60083437/a0737b0a-3924-4749-9ccb-350729db0097)


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.
- You can mail me at [![Mail](https://img.shields.io/badge/Gmail-tufahel96@gmail.com-red?logo=Gmail&logoColor=red&labelColor=black)](mailto:tufahel96@gmail.com) or ask any question at Slack, `Name: Tufahel`

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-04 01:19 UTC, merged