desktop-version-portfolio
Hsuwaddyhtat22/Portfolio pull request #4
Opened 2023-06-08 09:23 UTC by Hsuwaddyhtat22

In this desktop version
_change the style of HTML
-change the style of CSS
_rebuild to seem website page

2023-06-08 11:53 UTC, stanleySimeon requested changes
# Hi @Errytagedesign, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy-downsized.gif?cid=29caca753qc7ds307dmdk1qnte9yg2f3ese9hqc4qobqy07b&ep=v1_gifs_search&rid=giphy-downsized.gif&ct=g)

## Highlights
- Correct use of Gitflow ✔️
- Linter checks are passed ✔️
- Good PR description ✔️
- Meaningful commit messages ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- adding your readme file
- deploying your project
- stick to the design

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-08 11:53 UTC, stanleySimeon commented on index.html
>      </div>
Kindly, I suggest you remove this unnecessary closed tag. 😄

2023-06-08 11:53 UTC, stanleySimeon commented on index.html
> +            </div>
Greeting!

You are doing a great job so far, but there a few things you'll need to work on before moving to the next steps.

According to the Figma design, kindly I suggest you stick to the design as much as possible 1(e.g., font, colors, images, text, margins)1 using [the info of the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

> ## The Figma Design
>
><img width="891" alt="Screenshot 2023-06-08 at 7 31 57 AM" src="https://github.com/Hsuwaddyhtat22/Portfolio/assets/91237525/b5f4e9ce-4a74-4caf-8d9e-69ee88fc8e46">
>
> ## Your Design
>
><img width="1399" alt="Screenshot 2023-06-08 at 7 05 48 AM" src="https://github.com/Hsuwaddyhtat22/Portfolio/assets/91237525/06822717-304f-4a98-8c0d-6539389aded1">

2023-06-08 11:53 UTC, stanleySimeon commented on index.html
> +        <section class="version2" id="two">
As I mentioned above, you are doing a great job so far, but there a few things you'll need to work on before moving to the next steps.
Kindly, I suggest you update all your cards to stick to the Figma template. Please, take attention to details I said `all your cards`. 😄

According to the Figma design, kindly I suggest you stick to the design as much as possible 1(e.g., font, colors, images, text, margins)1 using [the info of the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

> ## The Figma Design
>
><img width="888" alt="Screenshot 2023-06-08 at 7 40 14 AM" src="https://github.com/Hsuwaddyhtat22/Portfolio/assets/91237525/117cbeb6-b34d-4f15-a80d-ba2cd798e51a">
>
> ## Your design
>
><img width="1397" alt="Screenshot 2023-06-08 at 7 09 45 AM" src="https://github.com/Hsuwaddyhtat22/Portfolio/assets/91237525/19b3c314-bbe1-492c-b8cd-9cc5181fb974">

2023-06-08 11:53 UTC, stanleySimeon commented on index.html
>          </section>
As I mentioned above, you are doing a great job so far, but there a few things you'll need to work on before moving to the next steps.

According to the Figma design, kindly I suggest you stick to the design as much as possible 1(e.g., font, colors, images, text, margins)1 using [the info of the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

> ## The Figma Design
>
><img width="891" alt="Screenshot 2023-06-08 at 7 44 39 AM" src="https://github.com/Hsuwaddyhtat22/Portfolio/assets/91237525/f006f7d0-6c55-4257-a60d-3e27ac843ca0">
>
> ## Your design
>
><img width="1400" alt="Screenshot 2023-06-08 at 7 14 17 AM" src="https://github.com/Hsuwaddyhtat22/Portfolio/assets/91237525/81ea2740-f4c1-4d61-ab8c-29a5ddacbcf9">

2023-06-08 11:53 UTC, stanleySimeon commented on index.html
> +        <div class="form-spree" id="spree">
As I mentioned above, you are doing a great job so far, but there a few things you'll need to work on before moving to the next steps.

According to the Figma design, kindly I suggest you update the form section to stick to the design as much as possible 1(e.g., font, colors, images, text, margins)1 using [the info of the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

> ## The Figma Design
>
><img width="892" alt="Screenshot 2023-06-08 at 7 45 56 AM" src="https://github.com/Hsuwaddyhtat22/Portfolio/assets/91237525/74ee5e4e-9bb8-4eb2-b375-308f201a8982">
>
> ## Your design
>
><img width="1399" alt="Screenshot 2023-06-08 at 7 19 20 AM" src="https://github.com/Hsuwaddyhtat22/Portfolio/assets/91237525/7f5be37f-4a70-426a-b369-a3faa7ed8542">

2023-06-08 16:10 UTC, tufoinnkuo10 requested changes
Hi @Hsuwaddyhtat22 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ Linter error checks validated
✅ Documented your work professionally
✅ figma version well followed.



---[optional] You can remove the live-demo section since it is not yet deployed.
Required Changes ♻️
Check the comments under the review
Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2023-06-08 16:10 UTC, tufoinnkuo10 commented on index.html
> +            <section class="version2" id="two">
- [optional] please kindly centralize your cards and the about section. They are all aligned to the left.

![Screenshot (1118)](https://github.com/Hsuwaddyhtat22/Portfolio/assets/65298048/c3a3668c-90cb-42c9-a1d7-1e41ba10dab1)

2023-06-08 16:10 UTC, tufoinnkuo10 commented on index.html
> +                <div class="grape">
- [ ] please, like the previous reviewer noted, kindly make the tech skill horizontal like in the original design.
yours
![Screenshot (1117)_LI](https://github.com/Hsuwaddyhtat22/Portfolio/assets/65298048/433e785a-aba4-45c7-8d0f-d4e42c9f8dfb)
original
![Screenshot (1116)_LI](https://github.com/Hsuwaddyhtat22/Portfolio/assets/65298048/7a8bf549-f183-4feb-823a-d834c28e1cd4)

2023-06-08 16:10 UTC, tufoinnkuo10 commented on index.html
> +            <div class="form-spree" id="spree">
- [ ] please, while making changes you might introduce other errors. Please make the contact section full width. You can set it to 100% and set the background position to cover. This will fit the original design
yours
![Screenshot (1114)_LI](https://github.com/Hsuwaddyhtat22/Portfolio/assets/65298048/f2f3204e-a805-4dd2-8248-09a3551b2e3c)
original
![Screenshot (1109)](https://github.com/Hsuwaddyhtat22/Portfolio/assets/65298048/886a0d17-2461-4300-bf26-24f8ff937d62)

2023-06-09 10:38 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @Hsuwaddyhtat22  

Your project is complete! Great job for making the requested changes 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- design well followed
- No linter errors


---[optional] You can remove the live demo section since your project is not yet deployed.
--- [optional] Please ensure to make your commit messages descriptive enough. nice work.
<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-09 10:38 UTC, tufoinnkuo10 commented on index.html
> +
- [optional] please ensure your cards are well responsive until it reaches the desktop version.

2023-06-09 10:38 UTC, tufoinnkuo10 commented on index.html
> +                </p>
- [optional] nice job centralizing your cards. Please kindly try to reduce the gap between the card and the text like in the original design
yours
![Screenshot (1128)_LI](https://github.com/Hsuwaddyhtat22/Portfolio/assets/65298048/620cfb35-5f6d-4c82-a80b-5afffdc80bb0)
figma
![Screenshot (1129)](https://github.com/Hsuwaddyhtat22/Portfolio/assets/65298048/1991f196-46c7-47ff-bec1-6e91d835f390)

2023-06-09 10:41 UTC, merged