Mobile hamburger
Hsuwaddyhtat22/Portfolio pull request #7
Opened 2023-06-19 18:12 UTC by Hsuwaddyhtat22

In this mobile-menu project.
-Add javascript (DOM)
-Add CSS for more styling
_linters for check

2023-06-20 07:29 UTC, yusufyusie commented on index.js
> +const closetag = document.querySelector(".close-tag");
[Required] I think using a CSS selector close-tag that is used to close taps to disappear and you add a dom querySelector but you are not set an event handler which addEveventListener() method

2023-06-21 10:16 UTC, bienvenuushindi requested changes
### Hi Team,

Good job imeplementing most of the project requirements!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Github flow is used correctly. ✔


## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below.

## [Optional] suggestions:

- [ ] Please check the inline comments below.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-06-21 10:16 UTC, bienvenuushindi commented on index.html
> +                <div class="hamburger">
:orange_circle: [OPTIONAL] Please use the button tag for the close element, rather than the div tag. This is the more semantic tag for this element, and it will make your code more accessible to users with disabilities.

```
<button class="hamburger">
      <div class="bar"></div>
      <div class="bar"></div>
      <div class="bar"></div>
</button>
```

2023-06-21 10:16 UTC, bienvenuushindi commented on index.html
> +        <script src="/index.js"></script>
:red_circle: [REQUIRED] Currently, if you try to run your code in your project in the browser there is a greater chance for your script to not work which was my case before I fix the bug myself in order to review the project. Please make sure you always add the dot to the src attribute when you are specifying a relative path. This will help to prevent errors in the future. 

The dot (.) is important because it tells the browser to look for the file relative to the current file.

I have updated  that line with the below code 

` <script src="./index.js"></script>`

**Notice the dot before the` /index`**

2023-06-21 11:24 UTC, skyv26 approved these changes
## Hi @Hsuwaddyhtat22, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## STATUS: APPROVED 🟢 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOGJmZWM5NmRjYjQ5ZjZjMjgzYTg1MzRlNDk0MDg5ZTZiM2I3YTk1NSZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/fYlennPcKut8gjKOZD/giphy.gif)

## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implement the features ✅ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-22 11:26 UTC, merged