Popup window
Hsuwaddyhtat22/Portfolio pull request #9
Opened 2023-06-22 12:24 UTC by Hsuwaddyhtat22

In popup project I modified HTML and CSS and javascript.I did for more styling for my webpage.
_check for linter errors

2023-06-22 12:59 UTC, V-Blaze requested changes
## Hi @Hsuwaddyhtat22 , 

## Required changes 🖊️ 
# Almost there 🟡 🟦 🟨 

![almost-there](https://user-images.githubusercontent.com/107632780/229242540-644ade4a-fe15-4f4c-a38b-6ded70cc4e8b.gif)


Great work so far, You have come a long way, keep moving forward👏 👍  
You've done well implementing the project requirements, but there are still some issues I think you need to improve on. 😄 👋 


 ## Highlights
- Readme looks professional✔
- Correct Github flow👋 
-  Pop-up opens and close correctly ✔

 ## Required Changes ♻️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-22 12:59 UTC, V-Blaze commented on index.html
> +                            </p>
- [ ] You have done great so far. :+1: :+1: But there are some requirements you need to meet before moving to the next milestone.
- [ ] As stated in the project requirement, this pop-up modal needs to be generated randomly inside the javascript file. You are meant to have a javascript function that generates this modal and appends its on the page when a user clicks on any of the projects. I'll suggest you remove the hardcoded content an implement this. :+1: :100: 
- [ ] Also looking at your current design, your pop-up doesn't fully match the Figma design, I'll suggest you look at the Figma design and try to replicate the design as that's part of the requirement for this milestone. :+1: :+1: 

- - Your current design:
![Selection_072](https://github.com/Hsuwaddyhtat22/Portfolio/assets/107632780/82d80f30-7f2d-4618-af62-e9e4c1643f4d)

- - Figma design:
![Screenshot from 2023-06-22 13-37-59](https://github.com/Hsuwaddyhtat22/Portfolio/assets/107632780/0ff1f682-e6c5-47a6-ab1b-996c969101cc)

2023-06-22 12:59 UTC, V-Blaze commented on index.html
> +                                </li>
> You need to update the main page so that the projects section is created dynamically using the information stored in that JavaScript object. Remember, all of the HTML in that section is created when the page loads.

- [ ] As stated in the project requirement, you are meant to remove the hardcoded works section. The purpose of having the array of projects in your `index.js` file is for you to dynamically generate this section of projects with javascript and append it to the page once the website loads. :+1: To meet the project requirement, I'll suggest you remove the harder coded list of projects here and write a javascript function that generates and appends it to the DOM. :+1: :+1:

2023-06-22 12:59 UTC, V-Blaze commented on index.html
> +                    <div class="form-footer">
- [OPTIONAL] This is not part of the requirement for this milestone, But currently, it seems that the stles for your form section are not working correctly, I'll suggest you fix this as your portfolio is meant to look professional at each point. :+1: :+1: 

- - Screenshot:
![Screenshot from 2023-06-22 13-40-32](https://github.com/Hsuwaddyhtat22/Portfolio/assets/107632780/b1d9d207-83d8-4fd2-94b9-3fd735a7bf67)

2023-06-22 12:59 UTC, V-Blaze commented on index.js
> +    ShowModal(3);
- [ ] In order to save computational time and make your codebase clean, I think it would be better to assign a common classname for all the `see-projects buttons`, use `document.querySelectorAll('.projectclassname')`, loop through it (perhaps `forEach`) and add eventListener to the current element in the iteration.

- - Example snippet:
![Screenshot from 2023-06-22 13-57-55](https://github.com/Hsuwaddyhtat22/Portfolio/assets/107632780/7364584c-f363-46de-8955-74e3d5f7d49c)

2023-06-23 10:38 UTC, Cabraham1 requested changes
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Hey @Hsuwaddyhtat22   :wave:

## Highlights :1st_place_medal:

✔️ Following Gitflow
✔️ Following some requirements

Good job on implementing some of the requirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:
# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers, and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-23 10:38 UTC, Cabraham1 commented on index.html
> +                  <img src="assets/images/icons/Icon -GitHub.png" alt="See Source Icon">
- [ ] Nice work so far 👍🏿 , As stated by the previous code reviewer,  you are meant to remove the hardcoded works section and generate them dynamically using a javascript array. The purpose of having the array of projects in your index.js file is for you to dynamically generate this section of projects with javascript and append it to the page once the website loads. 👍 To meet the project requirement, I'll suggest you remove the harder coded list of projects here and write a javascript function that generates and appends it to the DOM.

2023-06-23 10:38 UTC, Cabraham1 commented on index.html
> +                    <img class="project-img desktop right " src="assets/images/samples/desktop/Snapshoot-Portfolio2.png " alt="Portfolio 2 " />
- [ ] Nice work so far 👍🏿 , As stated by the previous code reviewer,  you are meant to remove the hardcoded works section and generate them dynamically using a javascript array. The purpose of having the array of projects in your index.js file is for you to dynamically generate this section of projects with javascript and append it to the page once the website loads. 👍 To meet the project requirement, I'll suggest you remove the harder coded list of projects here and write a javascript function that generates and appends it to the DOM.

2023-06-23 10:38 UTC, Cabraham1 commented on index.html
> +                    <img class="project-img desktop " src="assets/images/samples/desktop/Snapshoot-Portfolio3.png " alt="Portfolio 3 " />
- [ ] Nice work so far 👍🏿 , As stated by the previous code reviewer,  you are meant to remove the hardcoded works section and generate them dynamically using a javascript array. The purpose of having the array of projects in your index.js file is for you to dynamically generate this section of projects with javascript and append it to the page once the website loads. 👍 To meet the project requirement, I'll suggest you remove the harder coded list of projects here and write a javascript function that generates and appends it to the DOM.

2023-06-23 10:38 UTC, Cabraham1 commented on index.html
> +                    </div>
- [ ] Nice work so far 👍🏿 , As stated by the previous code reviewer,  you are meant to remove the hardcoded works section and generate them dynamically using a javascript array. The purpose of having the array of projects in your index.js file is for you to dynamically generate this section of projects with javascript and append it to the page once the website loads. 👍 To meet the project requirement, I'll suggest you remove the harder coded list of projects here and write a javascript function that generates and appends it to the DOM. 
 - [ ]

2023-06-23 10:38 UTC, Cabraham1 commented on index.html
> +                        </div>
- [ ] Nice work so far 👍🏿 , As stated by the previous code reviewer,  you are meant to remove the hardcoded works section and generate them dynamically using a javascript array. The purpose of having the array of projects in your index.js file is for you to dynamically generate this section of projects with javascript and append it to the page once the website loads. 👍 To meet the project requirement, I'll suggest you remove the harder coded list of projects here and write a javascript function that generates and appends it to the DOM.

2023-06-23 12:27 UTC, aamirkhan2478 approved these changes
Hi @Hsuwaddyhtat22, 

![GIF](https://www.funimada.com/assets/images/cards/big/congrats-7.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✅ You used Gitflow correctly :+1: 
✅ No linter error :+1: 
✅ Good commit messages :+1: 
✅ Good descriptive PR :+1: 
✅ Well done :clap: you did all changes given by the previous reviewer :+1: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-23 12:33 UTC, merged